/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/W5_LOD2.glb -t 
Made generic by foundway. Assuming only one mesh and one bone.
*/

import * as THREE from 'three'
import React, { JSX, useEffect } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'
import { SkeletonUtils } from 'three-stdlib'
import { useAnimationStore } from '../store/useAnimationStore'
import { useModelStore } from '../store/useModelStore'
import { Handle, HandleTarget } from '@react-three/handle'

export const Character = (props: JSX.IntrinsicElements['group']) => {  
  const { currentAnimation } = useAnimationStore()
  const { models } = useModelStore()
  const modelUrl = models[models.length - 1] || 'Duck.glb'
  const { scene, animations } = useGLTF(modelUrl)
  const group = React.useRef<THREE.Group>(null)
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene])
  const { actions } = useAnimations(animations, group)

  clone.traverse((child) => {
    console.log(child)
  })

  useEffect(() => {
    actions[currentAnimation]?.reset().fadeIn(0.5).play()
    return () => {
      actions[currentAnimation]?.fadeOut(0.5)
    }
  }, [currentAnimation])

  return (
    <HandleTarget>
      <group ref={group} {...props} dispose={null} renderOrder={-100}>
        <Handle translate={{ x: true, y: true, z: true }} scale={false} >
          <primitive object={clone} />
        </Handle>
      </group>
    </HandleTarget>
  )
}


